name: Create and publish a Docker image to hub.docker.com

on:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository == 'henriksson-lab/demo_elasticnet'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: mahogny83/demo_elasticnet
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: Dockerfile
          tags: "20240119-171300"
